# .rubocop.yml
# Style/EmptyLinesAroundBody:
#   Enabled: false
#
AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false
